version: "3.9"

services:
  # --- DATABASE ---
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file:
      - ./services/user-service/.env   # both will reuse credentials
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- USER SERVICE ---
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - postgres
    env_file:
      - ./services/user-service/.env.docker
    ports:
      - "8081:8081"
    restart: always

  # # --- PRODUCT SERVICE ---
  # product-service:
  #   build:
  #     context: ./services/product-service
  #     dockerfile: Dockerfile
  #   container_name: product-service
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./services/product-service/.env
  #   ports:
  #     - "8082:8082"
  #   restart: always
  #
  # # --- API GATEWAY ---
  # api-gateway:
  #   build:
  #     context: ./api-gateway
  #     dockerfile: Dockerfile
  #   container_name: api-gateway
  #   depends_on:
  #     - user-service
  #     - product-service
  #   env_file:
  #     - ./api-gateway/.env
  #   ports:
  #     - "8080:8080"
  #   restart: always

volumes:
  postgres_data:

